### ISSUE TITLE
Unable to run `mock-pb g`

### ISSUE THREAD

**Issue by samfweb** [JasonkayZK/mock-protobuf.js#6]
Getting the following issues attempting to run `mock-pb g` on mac.

Looks like a restify issue.

```
/Users/sam/Library/pnpm/global/5/.pnpm/restify@8.6.1/node_modules/restify/lib/request.js:848
    Request.prototype.closed = function closed() {
                             ^

TypeError: Cannot set property closed of #<Readable> which has only a getter
    at patch (/Users/sam/Library/pnpm/global/5/.pnpm/restify@8.6.1/node_modules/restify/lib/request.js:848:30)
    at Object.<anonymous> (/Users/sam/Library/pnpm/global/5/.pnpm/restify@8.6.1/node_modules/restify/lib/server.js:33:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Users/sam/Library/pnpm/global/5/.pnpm/restify@8.6.1/node_modules/restify/lib/index.js:10:14)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)

Node.js v20.9.0
```

Cheers for the package, any help is appreciated.

**Comment by JasonkayZK** [comment]
> Getting the following issues attempting to run `mock-pb g` on mac.
> 
> Looks like a restify issue.
> 
> ```
> /Users/sam/Library/pnpm/global/5/.pnpm/restify@8.6.1/node_modules/restify/lib/request.js:848
>     Request.prototype.closed = function closed() {
>                              ^
> 
> TypeError: Cannot set property closed of #<Readable> which has only a getter
>     at patch (/Users/sam/Library/pnpm/global/5/.pnpm/restify@8.6.1/node_modules/restify/lib/request.js:848:30)
>     at Object.<anonymous> (/Users/sam/Library/pnpm/global/5/.pnpm/restify@8.6.1/node_modules/restify/lib/server.js:33:1)
>     at Module._compile (node:internal/modules/cjs/loader:1241:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
>     at Module.load (node:internal/modules/cjs/loader:1091:32)
>     at Module._load (node:internal/modules/cjs/loader:938:12)
>     at Module.require (node:internal/modules/cjs/loader:1115:19)
>     at require (node:internal/modules/helpers:130:18)
>     at Object.<anonymous> (/Users/sam/Library/pnpm/global/5/.pnpm/restify@8.6.1/node_modules/restify/lib/index.js:10:14)
>     at Module._compile (node:internal/modules/cjs/loader:1241:14)
> 
> Node.js v20.9.0
> ```
> 
> Cheers for the package, any help is appreciated.

You are correct, it was a restify issue one year ago. I didn't notice that they've already fix that problem here:

- https://github.com/restify/node-restify/pull/1929

I've already update the restify dependency version and test with Node 18, 20 and 21, all works fine now.

And a new version `v1.1.2` has been released for mock-protobuf.js.

You can install the latest version with:

```shell
npm i mock-pb-cli@latest -g
```

Also, thanks for using mock-protobuf.js! ❤️

**Comment by samfweb** [comment]
Thanks @JasonkayZK :)
